"""Choice resolution contract that produces deltas and player-model observations."""

from __future__ import annotations

from typing import Any

from contracts import (
    ActionType,
    Observation,
    Outcome,
    SceneSpec,
    validate_observation,
    validate_outcome,
    validate_scene_spec,
)


def resolve_choice(
    state: Any,
    scene_spec: SceneSpec,
    choice: ActionType,
) -> tuple[Outcome, Observation]:
    """
    Resolve a player choice against the current scene and state snapshot.

    Args:
        state: Current game state snapshot/reference used for read-only context
            during resolution. Implementations may inspect player stats, flags,
            location, tension, and active plot threads.
        scene_spec: Scene specification previously generated by 'DMPolicy'.
            Expected to contain choice metadata, success conditions, effects, and
            tags needed to determine outcomes.
        choice: Player-selected action label or action identifier.

    Returns:
      outcome: dict (state deltas only)
      observation: dict (for PlayerModel)

    Outcome Format (conceptual contract):
        The 'outcome' dictionary must contain delta-style updates only, never
        direct 'GameState' mutation. Typical keys may include:
        - 'player': health/resource deltas or location changes
        - 'inventory': additions/removals
        - 'flags': set/unset operations
        - 'relationships': NPC affinity deltas
        - 'tension_delta': narrative tension adjustment
        - 'plot_threads': thread progress/status updates
        - 'events': event records to append to world memory

    Observation Format (conceptual contract):
        The 'observation' dictionary is evidence for 'PlayerModel.observe(...)'
        and should describe what the player chose, not how the world mutated.
        Typical keys may include:
        - 'choice_id' or 'choice_tags'
        - 'risk_level'
        - 'social_intent'
        - 'exploration_intent'
        - 'aggression_signal'
        - 'success' / 'failure'

    Constraints:
        - No direct 'GameState' mutation is allowed here.
        - This function computes outputs only.
        - 'GameState.apply_outcome(...)' is responsible for applying 'outcome'.
    """
    validate_scene_spec(scene_spec)

    # TODO: Compute 'outcome' deltas and 'observation' evidence from 'choice'.
    # Placeholder payloads preserve the canonical contract shape during
    # scaffolding and allow boundary validation stubs to be wired now.
    outcome: Outcome = {}
    observation: Observation = {"choice": choice}

    validate_outcome(outcome)
    validate_observation(observation)
    _ = state
    return outcome, observation
