"""Scene rendering and choice listing interfaces (read-only, no state mutation)."""

from __future__ import annotations

from typing import Any

from contracts import ActionType, SceneSpec, validate_scene_spec


def render_scene(scene_spec: SceneSpec, templates: dict[str, Any], content_db: Any) -> str:
    """
    Render a textual scene description from a scene specification and templates.

    Args:
        scene_spec: Read-only scene specification generated by 'DMPolicy'.
            Expected to contain template identifiers, metadata, and 'text_vars'
            values needed to render final prose.
        templates: Template dictionary (typically from
            'ContentDB.list_templates()'), containing text snippets or grouped
            templates keyed by template ID.
        content_db: Read-only content database handle for resolving referenced
            assets (locations, NPC names, item labels, etc.) during rendering.

    Returns:
        Rendered scene text as a string.

    Interaction and Constraints:
        - Performs template variable substitution only.
        - 'scene_spec["text_vars"]' is the primary source of substitution values.
        - May read additional content metadata via 'content_db'.
        - Must not mutate 'scene_spec', 'templates', 'content_db', or 'GameState'.
    """
    validate_scene_spec(scene_spec)
    # TODO: Render scene text using template lookup and 'scene_spec["text_vars"]'.
    pass


def list_choices(scene_spec: SceneSpec) -> list[ActionType]:
    """
    Extract player-facing choice labels from a scene specification.

    Args:
        scene_spec: Read-only scene specification selected by 'DMPolicy',
            expected to include a structured list of actions/choices.

    Returns:
        Ordered list of canonical action identifiers presented as selectable
        choices. A future UI layer may map these to display labels.

    Interaction and Constraints:
        - Reads only from 'scene_spec'.
        - Should preserve authored or policy-defined choice ordering.
        - Must not perform any mutation or side effects.
    """
    validate_scene_spec(scene_spec)
    # TODO: Return ordered action identifiers from the validated scene spec.
    pass
